#!/bin/sh
if [ "$(id -u)" -ne 0 ]; then
    echo "Must be run as root."
    exit
fi

URL=https://download.mediathekview.de/stabil/MediathekView-latest-linux.deb
TARGET=/var/tmp/mediathekview.deb
echo "Downloading deb file..."
curl -sL "$URL" -o "$TARGET" && \
    dpkg -i "$TARGET" 

rm -f "$TARGET"
